# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

foreach file (
  exports.zsh
  settings.zsh
  functions.zsh
  aliases.zsh
  mappings.zsh
  plugins.zsh
) {
  source $ZSH_CONFIG_PATH/config/$file
}
unset file

# Connect space
if [[ $(uname) == "Darwin" ]]; then
    source "$ZSH_CONFIG_PATH"/space/work.zsh
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

[ ! -f ~/.fzf.zsh ] || source ~/.fzf.zsh
