# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

foreach file (
  exports.zsh
  settings.zsh
  functions.zsh
  aliases.zsh
  mappings.zsh
  plugins.zsh
  abbr.zsh
) {
  source $ZSH_CONFIG_PATH/config/$file
}
unset file

# Connect space
if [[ $(uname) == "Darwin" ]]; then
    source "$ZSH_CONFIG_PATH"/space/work.zsh
fi

# Final settings abbr highlight
if [[ -n $FAST_HIGHLIGHT ]]; then
  for abbr in ${(f)"$(abbr list-abbreviations)"}; do
    if [[ $abbr != *' '* ]]; then
      register_single_word_chroma ${(Q)abbr}
    fi
  done
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# FZF init
if command -v fzf &> /dev/null; then source <(fzf --zsh); fi
